title: PRiSM 2026
full_title: Precise Mixed Reality for Surgical and Medical Interventions (PRiSM)
subtitle: MICCAI 2026 Workshop
description: Advancing mixed reality for surgical and medical interventions
logo: /assets/img/workshop_logo.png
contact_email: Prism.miccai2026@gmail.com
workshop_location: Abu Dhabi, UAE
remote_theme: Bilal2453/cayman-docs

# Layout
show_social: false
show_excerpts: false
show_sidebar: false

navigation:
  name_over_title: false
  toc_parameter: []

# # Menu
# navigation:
#   - {file: "index.html", title: "Home", icon: home}
#   - {file: "people.md", title: "People", icon: address-card}
#   - {file: "/program.md", title: "Program", icon: address-card}

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
